/** @type {import('tailwindcss').Config} */
module.exports = {
  corePlugins: {
    preflight: false,
    container: false,
  },
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './docs/**/*.{js,ts,jsx,tsx,md,mdx}',
    './src/**/*.{js,ts,jsx,tsx,md,mdx}',
  ],
  daisyui: {
    themes: [
      {
        dark: {
          primary: '#8A9DE4',
          'primary-content': '#313851',
          secondary: '#A0A9CB',
          'secondary-content': '#393C46',
          accent: '#ECC94B',
          'accent-content': '#362E11',
          neutral: '#323940',
          'neutral-content': '#B4CADC',
          'base-100': '#04050E',
          'base-200': '#080912',
          'base-300': '#11111a',
          'base-content': '#FFFFFF',
          info: '#4299E1',
          'info-content': '#16354F',
          success: '#48BB78',
          'success-content': '#164128',
          warning: '#ED8936',
          'warning-content': '#492C13',
          error: '#F56565',
          'error-content': '#4C1F1F',
        },
      },
      {
        light: {
          primary: '#00a0d2',
          'primary-content': '#04050E',
          secondary: '#00ff7b',
          'secondary-content': '#04050E',
          accent: '#357c00',
          'accent-content': '#d6e5d0',
          neutral: '#26292e',
          'neutral-content': '#cfd0d1',
          'base-100': '#FFFFFF',
          'base-200': '#f2f2f2',
          'base-300': '#ebebeb',
          'base-content': '#131616',
          info: '#62c6ff',
          'info-content': '#030e16',
          success: '#1ac000',
          'success-content': '#000e00',
          warning: '#cd7300',
          'warning-content': '#0f0500',
          error: '#ff004f',
          'error-content': '#160002',
        },
      },
    ],
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
}
